baseURL = "https://sherry-sr.github.io/"
languageCode = "en-us"
title = "Rui Shen"

[params]
    firstName = "Rui"
    lastName = "Shen"
    address = "Baltimore, MD"
    phone = "1-443-248-2532"
    contactNote = "Johns Hopkins University"
    profileImage = "img/me.jpg"
    email = "sherry.shen@jhu.edu"
    description = "Rui Shen webpage"
    favicon = "favicon.jpg"
    # what sections
    showProjects = true
    showSkills = true
    showOpenSource = false
    showPublications = true
    showExperience = true
    showEducation = true
    showBlog = true
    showQr = true

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/Sherry-SR"

[[params.handles]]
    name = "Linkedin"
    link = "https://www.linkedin.com/in/rui-shen-b99a91131"